[package]
name = "qiitadon-archive"
version = "0.1.0"
authors = ["gemmaro <gemmaro.dev@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.19"
heck = "0.3.1"
itertools = "0.10.0"
serde = "1.0.118"
serde_derive = "1.0.118"
serde_json = "1.0.60"
